# ===================================================================
# Spring Boot configuration for the "prod" profile.
# This configuration overrides the application.yml file.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  level:
    ROOT: INFO
    com.example.demo: debug

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    service-url:
      defaultZone: ${application.register.discovery-url}/eureka/

spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false
    add-properties: false
  datasource:
    url: ${DATABASE_URL}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${USERNAME_POSTGRES:postgres}
    password: ${PASSWORD_POSTGRES:postgres}
    hikari:
      pool-name: Hiraki
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      #Hibernate can then execute SQL statements in batches, therefore reducing the number of database network roundtrips
      #between 5 and 30
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      #Hibernate can then prevent in-memory pagination when join fetching a child entity collection
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      #Hibernate entity queries can then make better use of statement caching and fewer entity queries will have to be compiled while varying the number of parameters passed to the in query clause
      hibernate.query.in_clause_parameter_padding: true
      # Configuration to Cache Provider Hazelcast
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: bets
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
server:
  port: ${PORT:9999}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
# ===================================================================
# App specific properties
# ===================================================================
application:
  register:
    discovery-url: http://admin:eureka@localhost:8761
  cache: # Cache configuration
    time-to-live-seconds: 3600
    backup-count: 1
    management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
      enabled: false
      update-interval: 3
      url: http://localhost:8180/mancenter
  security:
    client-authorization:
      access-token-uri: http://uaa/oauth/token
      token-service-id: uaa
      client-id: internal
      client-secret: internal
  signature-verification:
    public-key-endpoint-uri: http://uaa/oauth/token_key
    #ttl for public keys to verify JWT tokens (in ms)
    ttl: 3600000
    #max. rate at which public keys will be fetched (in ms)
    public-key-refresh-rate-limit: 10000